name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Ganti dengan nama cabang utama Anda jika berbeda

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Pastikan versi Node.js Anda sesuai dengan kebutuhan Docusaurus

      - name: Install dependencies
        run: npm install

      - name: Clear Build
        run: rm -rf build 

      - name: Build Docusaurus
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/build